project:
  type: book
execute:
  freeze: auto
book:
  title: "TEOTIL3 Lillestrøm"
  site-url: https://nivanorge.github.io/teotil3_lillestrom/
  repo-url: https://github.com/NIVANorge/teotil3_lillestrom/blob/main/README.md

  chapters:
    - index.qmd
    - intro.qmd
    - data-sources-models.qmd
    - method.qmd
    - part: Results
      chapters:
        - sagelva.qmd
        - nitelva.qmd
        - leira.qmd
        - romua.qmd
        - jeksla.qmd
        - aa.qmd
        - gansaa.qmd
    - summary.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true