---
title: "Data sources and models"
number-sections: true
---

## Water chemistry {#sec-water-chem}

Water chemistry data are available from [Vannmiljø](https://vannmiljo.miljodirektoratet.no/), the national water chemistry database maintained by Miljødirektoratet. At the start of this project, Lillestrøm kommune provided a list monitoring stations with good quality data in each catchment of interest. 

Catchments in Norway are also divided into waterbodies according to Vannforskriften, which is Norway's implementation of the EU Water Framework Directive (WFD). The [Vann-nett portal](https://vann-nett.no/) uses data from Vannmiljø to assign each waterbody a status (high, good, moderate, poor or bad) based thresholds defined in Vannforskriften for each parameter or quality element.

@tbl-chem-mon lists the main monitoring stations in each catchment and identifies the corresponding WFD waterbody for each station. The WFD status for a waterbody displayed in Vann-nett may combine data from multiple stations, so for this analysis two sets of data were downloaded: (i) monitoring data for the specific stations suggested by Lillestrøm kommune, and (ii) all monitoring data used to assign status for each waterbody in Vann-nett. The first dataset provides the best available time series for individual points, whereas the second offers a more aggregated assessment (often with greater variability) and reflects the data used by water managers to set water quality targets.

All water chemistry data were downloaded programmatically via Python using the Vannmiljø and Vann-nett Application Programming Interfaces (APIs). See [notebook 02](https://github.com/NIVANorge/teotil3_lillestrom/blob/main/code/02_vannmiljo_vann-nett_nve.ipynb) for details.

```{python}
#| label: tbl-chem-mon
#| tbl-cap: "Water chemistry monitoring stations within the catchments of interest."
#| echo: false

import pandas as pd

# Read site data
xl_path = r"./data/lillestrom_monitoring_sites.xlsx"
df = pd.read_excel(xl_path, sheet_name="chem_stns")

# Tidy
names_dict = {
    "catchment": "Nedbørfelt",
    "station_id": "Vannmiljø-ID",
    "station_name": "Stasjonsnavn",
    "regine": "REGINE-ID",
    "wb_id": "Vannforekomst-ID",
    "wb_name": "Vannforekomstnavn",
    "lon": "Lengdegrad",
    "lat": "Breddegrad",
}
df = df.rename(columns=names_dict)[list(names_dict.values())]

# Format
num_cols = ["Lengdegrad", "Breddegrad"]
txt_cols = [c for c in df.columns if c not in num_cols]
fmt = {c: "{:.6f}" for c in num_cols}

# Style
(
    df.style.format(fmt).hide(axis="index")
    # Center column headers
    .set_table_styles(
        [{"selector": "th.col_heading", "props": [("text-align", "center")]}]
    )
    # Center text columns
    .set_properties(subset=txt_cols, **{"text-align": "center"})
    # Right-align numeric columns
    .set_properties(subset=num_cols, **{"text-align": "right"})
)
```

## Water discharge {#sec-discharge}

Water discharge is monitored by Norges vassdrags- og energidirektorat (NVE). However, discharge monitoring for the water chemistry stations of interest (@tbl-chem-mon) is limited. The outflow of Sagelva is monitored by NVE discharge station `2.1185.0`, which corresponds directly to Vannmiljø station ID `002-46599`. The only other NVE station with data within the catchments of interest is at Kråkfoss (`2.279.0`) on Leira, but this is much further upstream than any of the chemistry monitoring stations.

In cases where direct monitoring of discharge is not available, NVE publishes modelled estimates of daily discharge via the [Grid Time Series (GTS) API](https://api.nve.no/doc/gridtimeseries-data-gts/). Simulations are based on a spatially distributed version of the [HBV model](https://www.nve.no/vann-og-vassdrag/vannets-kretsloep/analysemetoder-og-modeller/hbv-modellen/) developed by [Beldring *et al.* (2003)](https://hess.copernicus.org/articles/7/304/2003/hess-7-304-2003.html). For catchments without direct monitoring, the GTS API provides the best available estimates of river flow, but NVE's model does not include detailed flow-routing or water transfers between catchments (e.g. for drinking water or hydropower). It is therefore necessary to evaluate the GTS API for catchments around Lillestrøm kommune.

@fig-nve-target-plot compares simulations from NVE's model with observed discharge at stations `2.1185.0` (Sagelva) and `2.279.0` (Kråkfoss, Leira). The comparison period extends from 2015 to 2025 for Sagelva and from 1980 to 2025 for Kråkfoss. Overall, the model performs reasonably well, with Nash-Sutcliffe efficiencies of approximately 0.6 at both sites. However, results indicate a slight negative systematic bias (y-axis), suggesting that NVE's model tends to underpredict discharge on average. The principal limitation is that the model underestimates discharge variability (x-axis), producing a smoother signal with lower standard deviation than the observed series. This tendency is common in hydrological models.

Based on this assessment, NVE's modelled discharge appears to be suitable for estimating nutrient loads at monitoring stations where direct discharge measurements are not available. This means all stations listed in @tbl-chem-mon except `002-46599`.

![Target plot comparing NVE's discharge simulations to measured discharge at NVE stations `2.1185.0` (Sagelva) and `2.279.0` (Kråkfoss, Leira). The y-axis shows normalised bias between simulated and observed. The x-axis is the unbiased, normalised root mean square difference (RMSD) between simulated and observed data. The distance between a point and the origin is total RMSD. RMSD = 1 is shown by the solid circle (any point within this has positively correlated simulated and observed data and positive Nash-Sutcliffe scores); the dashed circle marks RMSD = 0.7.](./plots/nve_target_plot.png){#fig-nve-target-plot width=500 fig-align="center"}

## Nutrient inputs {#sec-nutrient-inputs}

In addition to monitoring data, source-specific nutrient inputs have been estimated from available national and regional datasets.

### Municipal wastewater {#sec-large-wastewater}

Municipal wastewater treatment plants with capacity ≥50 person equivalents (p.e.) are required to monitor and report nutrient discharges to Miljødirektoratet via ALTINN. These data are made available to NIVA as part of national scale modelling projects using TEOTIL3 (@sec-teotil3).

Raw data are cleaned and statistically interpolated using a methodology based on Statistisk Sentralbyrå's (SSB's) procedure for national wastewater statistics (e.g. [Berge & Hjertaas, 2024](https://www.ssb.no/natur-og-miljo/vann-og-avlop/artikler/kommunale-avlop-2023.ressursinnsats-gebyrer-utslipp-rensing-og-slamdisponering)). Where wastewater discharges are monitored, these values are used directly. Otherwise, discharges are estimated based on plant capacity (number of people connected, in p.e.) and assumed default treatment efficiencies that vary according to treatment type (provided by Miljødirektoratet; [here](https://github.com/NIVANorge/teotil3/blob/main/data/treatment_efficiencies_large_wastewater.csv)).

### Other wastewater {#sec-small-wastewater}

For small wastewater treatment plants (capacity <50 p.e.) and systems that are not connected to the municipal wastewater network (e.g. septic tanks), SSB compiles aggregated discharge statistics at municipality level. These sources are commonly referred to as "spredt avløp" (scattered wastewater discharges). For this project, Lillestrøm kommune provided a more detailed dataset, including locations of individual septic tanks and small treatment plants (minirenseanlegg), as well as information on stormwater and emergency overflows from the municipal wastewater network within the municipality.

For the modelling in this project, SSB data were used for all municipalities except Lillestrøm, where the more detailed, site-specific dataset was used instead. It should be noted, however, that SSB's dataset covers a longer time period than the Lillestrøm-specific data. Consequently, the spredt dataset prepared for this project provides higher spatial resolution within Lillestrøm kommune than standard national datasets, but with slightly reduced temporal resolution.

A detailed comparison of the national and Lillestrøm-specific spredt datasets is provided in [notebook 05](https://github.com/NIVANorge/teotil3_lillestrom/blob/main/code/05_estimate_overflows_and_spredt.ipynb).

### Industry {#sec-industry}

Data describing industrial discharges has been provided by Miljødirektoratet. Data collection is based on self-reporting from industry and reflects the
components regulated in the respective discharge permits. Data are consistent with the information made publicly available via the [Norske utslipp](https://www.norskeutslipp.no/) website.

### Agriculture {#sec-agriculture}

Annual estimates of nutrient losses from agriculture are made by NIBIO using the AGRITIL models (Kværnø *et al.*, 2024). These calculate losses of soil particles, phosphorus, nitrogen and organic carbon from agricultural land to first order streams. The models are based on empirical relationships developed using data from the [Agricultural Environmental Monitoring Programme (JOVA)](https://www.nibio.no/tema/miljo/jord-og-vannovervaking-i-landbruket).

### Urban {#sec-urban}

Estimates of nutrient runoff from urban areas have been made using typical runoff coefficients for Norwegian built-up areas taken from [Åstebøl *et al.* (2012)](https://www.miljodirektoratet.no/sharepoint/downloaditem?id=01FM3LD2XYMQWENJOBOVEL2YIHX3PUTEYP).

### Background {#sec-background}

Estimates of annual nutrient inputs from runoff in forest and upland areas are made by NIVA using long-term national monitoring data. Key datasets include the Norwegian "1000 Lakes" surveys in 1995 and 2019, and the "Trend lakes" project. See e.g. [de Wit et al. (2023)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2022GB007509) for an overview.  

## Water quality models {#sec-models}

### AGRITIL {#sec-agritil}

The AGRITIL models ([Kværnø *et al.*, 2024](https://nva.sikt.no/registration/0198cc63853e-ba89c1b2-539a-4fca-9592-b458c68496e2)) have been used to estimate nutrient losses from agricultural land to first-order streams. AGRITIL provides source-specific input data for agricultural runoff to TEOTIL3 (@sec-teotil3) and consists of separate empirical models for nitrogen (AGRITIL-N) and for suspended sediment, phosphorus and organic carbon (AGRITIL-SPC). The models are calibrated using data from Norwegian agricultural monitoring catchments (e.g. the [JOVA programme](https://www.nibio.no/tema/miljo/jord-og-vannovervaking-i-landbruket)) and are designed to quantify gross nutrient and sediment losses from agricultural areas under varying environmental conditions and management practices.

AGRITIL-N simulates losses of total nitrogen (TOTN) and nitrate (NO3) from agricultural land. Predicted nitrogen losses are influenced by factors such as runoff, nitrogen balance, soil type, climatic conditions, and the implementation of mitigation measures including winter vegetation cover, catch crops and reduced tillage.

AGRITIL-SPC simulates losses of suspended sediment (SS), total phosphorus (TOTP), phosphate (PO4) and total organic carbon (TOC). Model estimates are based on relationships between nutrient and sediment losses, hydrological conditions, soil properties, land use, erosion risk, and agricultural management practices.

AGRITIL estimates losses from agricultural land at the edge-of-field or first-order stream scale and does not account for nutrient retention occurring downstream. Downstream transport and retention processes are subsequently represented within TEOTIL3.

### TEOTIL3 {#sec-teotil3}

The TEOTIL3 model ([Sample *et al.*, 2024](https://www.miljodirektoratet.no/publikasjoner/2024/juli-2024/teotil3-en-modell-for-beregning-av--kildebaserte-tilforsler-via-elver-og--direktetilforsler-til-kyst/)) has been used to simulate source-apportioned nutrient inputs for each catchment of interest. TEOTIL3 was also used to estimate the load reductions required for Good Ecological Status (GES) under the Water Framework Directive, as well as the extent to which reductions might be achieved using combinations of measures (based on [Wallhead *et al.*, 2026](https://www.miljodirektoratet.no/publikasjoner/2026/april-2026/modellering-av-oslofjorden-scenarier-med-redusert-menneskelig-belastning-for-a-oppna-god-okologisk-tilstand/)).

TEOTIL3 is an annual mass balance model that simulates the following nutrients:

 * Total nitrogen (TOTN) and the main fractions of nitrogen: dissolved inorganic nitrogen (DIN) and total organic nitrogen (TON).
 * Total phosphorus (TOTP) and the main fraction of phosphorus: total dissolved phosphorus (TDP) and total particulate phosphorus (TPP).
 * Total organic carbon (TOC).
 * Suspended sediment (particles; SS).

TEOTIL3 includes a simple hydrological transport module that simulates nutrient retention in lakes, but not in rivers. The model considers nutrients from the following sources (using datasets described in @sec-nutrient-inputs):

 * Inputs from agriculture simulated by NIBIO using the AGRITIL models.
 * Discharges from large wastewater treatment plants (≥50 p.e.).
 * Direct inputs from industrial plants not connected to the municipal wastewater network.
 * Discharges from small wastewater treatment plants (<50 p.e.; referred to as "spredt avløp").
 * Nutrient runoff from urban areas.
 * Nutrient losses from aquaculture in seawater (not relevant for Lillestrøm kommune).
 * Atmospheric deposition of nitrogen directly to lake surfaces.
 * Natural background runoff from forest, upland and glacier areas.

TEOTIL3 does not include temporary sources of nutrients, such as construction sites or road building. The standard version of the model also omits overflows from the municipal wastewater network, but for this project the model has been extended to include overflow data provided by Lillestrøm kommune (see @sec-small-wastewater).