---
title: "References"
number-sections: true
css: styles.css
---

::: {.references}

Beldring S, Engeland K, Roald LA, Sælthun NR, Voksø A. 2003. *Estimation of parameters in a distributed precipitation-runoff model for Norway*. Hydrology and Earth System Sciences 7 (3) 304-316. [Tilgjengelig på nett](https://hess.copernicus.org/articles/7/304/2003/hess-7-304-2003.html).

Berge G & Hjertaas HW. 2024. *Kommunale avløp 2023. Ressursinnsats, gebyrer, utslipp, rensing og slamdisponering*. SSB rapport 2024/45. [Tilgjengelig på nett](https://www.ssb.no/natur-og-miljo/vann-og-avlop/artikler/kommunale-avlop-2023.ressursinnsats-gebyrer-utslipp-rensing-og-slamdisponering).

Helsel DR, Hirsch RM, Ryberg KR, Archfield SA, Gilroy EJ. 2020. *Statistical Methods in Water Resources*. U.S. Geological Survey Techniques and Methods, Book 4, Chapter A3. [Tilgjengelig på nett](https://doi.org/10.3133/tm4a3).

Hensel GR & Mæhlum T. 2025. *Mindre avløpsanlegg i spredt bebyggelse - Renseeffekt og reduksjonsfaktorer* NIBIO rapport 11 41. [Tilgjengelig på nett](https://hdl.handle.net/11250/3183748).

Kværnø S, Fischer F, Bechmann M. 2024. *AGRITIL - Nutrient loss model for agriculture - Modelling soil, organic carbon, nitrogen and phosphorus losses from Norwegian agricultural areas to water*. NIBIO rapport 10-43-2024. [Tilgjengelig på nett](https://nva.sikt.no/registration/0198cc63853e-ba89c1b2-539a-4fca-9592-b458c68496e2).

Meland A, Fyhn A, Kornstad T, Falk MI, Karlsson T, Vingerhagen R. 2023. *Overvåkning og klassifisering 2022: Fysisk-kjemiske kvalitetselementer*. Vannområde Leira-Nitelva rapport 02-J03. [Tilgjengelig på nett](https://elveliv.no/wp-content/uploads/2022-vannovervaking-i-vo-leira-nitelva.pdf).

Sample JE, Jackson-Blake LA, Vogelsang C, Kaste Ø. 2024. *TEOTIL3: En modell for beregning av kildebaserte tilførsler via elver og direktetilførsler til kyst*. NIVA rapport 7996-2024. [Tilgjengelig på nett](https://www.miljodirektoratet.no/publikasjoner/2024/juli-2024/teotil3-en-modell-for-beregning-av--kildebaserte-tilforsler-via-elver-og--direktetilforsler-til-kyst/).

Wallhead P, Staalstrøm A, Jackson-Blake LA, Kvile K, Frigstad H, Norling M, Rinde E, Murray C, Sample JE, Yakushev E, Ramon P, Christensen KH, Kristensen NM, Simonsen M, Kværnø SH, Fischer F, Bechmann M. 2026. *Modellering av Oslofjorden: scenarier med redusert menneskelig belastning for å oppnå god økologisk tilstand*. NIVA rapport 8186-2026. [Tilgjengelig på nett](https://www.miljodirektoratet.no/publikasjoner/2026/april-2026/modellering-av-oslofjorden-scenarier-med-redusert-menneskelig-belastning-for-a-oppna-god-okologisk-tilstand/).

de Wit HA, Garmo ØA, Jackson-Blake LA, Clayer F, Vogt RD, Austnes K, Kaste Ø, Gundersen CB, Guerrerro JL, Hindar A. 2023. *Changing water chemistry in one thousand Norwegian lakes during three decades of cleaner air and climate change*. Global Biogeochemical Cycles 37. [Tilgjengelig på nett](https://doi.org/10.1029/2022GB007509).

Åstebøl SO, Kjølholt J, Hvitved-Jacobsen T, Berg G, Saunes H. 2012. *Beregning av forurensing fra overvann*. COWI rapport A029838/137924. [Tilgjengelig på nett](https://www.miljodirektoratet.no/sharepoint/downloaditem?id=01FM3LD2XYMQWENJOBOVEL2YIHX3PUTEYP).