---
title: "Summary"
number-sections: true
---

This study uses monitoring and modelling to assess water quality status, trends in nutrient concentrations, and load reductions to achieve good ecological status (GES) for seven catchments with outflows within Lillestrøm kommune. @tbl-overall-summary summarises the main results for each catchment.

Agriculture and wastewater discharges are the dominant human sources of nutrients to catchments in this regions. All catchments considered are affected by eutrophication to some extent, with present-day water quality status for TOTN and TOTP ranging from *Moderate* to *Bad*. However, there are no increasing trends in mean annual concentrations of TOTN or TOTP, and several catchments show significant declining trends over time. In most catchments, including the four largest, TOC concentrations are significantly increasing. This is part of a broader regional pattern, which is most likely due to increasing concentrations of dissolved organic matter in forest and upload soils as catchments recover from acidification.

Nitelva and Leira (the two largest catchments) and Sagelva all have good long-term monitoring and are well suited to modelling using TEOTIL3. Monitoring and modelling for these catchments provide a broadly consistent picture of historic nutrient loads, except for TOTP in Nitelva, where there are questions over whether the monitoring data accurately represent fluxes of particulate phosphorous. Several catchments - most notably Jeksla and Gansåa - are too small to be modelled explicitly with TEOTIL3. In these catchments, model results are scaled using average conditions over a wider area, meaning results must be interpreted with caution. In these catchments, the monitoring data is also generally of lower quality, making it difficult to estimate load reduction targets robustly.

For most catchments, **significant load reductions will be required to reach GES for TOTN and TOTP**. 

Of the seven catchment considered, only Nitelva and Leira receive significant inputs from large municipal wastewater treatment plants. In the Leira catchment, recent upgrades to Gardermoen renseanlegg during 2025-6 mean that most of the potential improvements to wastewater handling in this catchment have already been achieved. In  Nitelva, the older treatment plants at Rotnes and Åneby are also in the process of being decommissioned, with effluent diverted to Nedre Romerike avløpsanlegg (NRA), which also reports high treatment efficiencies for nitrogen (although not as high as the new facility at Gardermoen). Several important upgrades to reduce wastewater discharges in these catchments are therefore already in progress.

For agriculture, recent modelling undertaken by NIBIO suggests that large reductions in TOTP and SS losses could be achieved in these catchments using traditional packages of agricultural measures corresponding to scenario A in [Wallhead *et al.* (2026)](https://www.miljodirektoratet.no/publikasjoner/2026/april-2026/modellering-av-oslofjorden-scenarier-med-redusert-menneskelig-belastning-for-a-oppna-god-okologisk-tilstand/). Scenario A assumes full implementation of measures covered by existing legislation within the five Environmental Requirement Zones (@sec-teo-scens), which should be completed in the coming years. **For all catchments except Leira, results suggest that measures equivalent to scenario A would be sufficient to achieve GES for TOTP**. For Leira, additional measures achieving TOTP reductions equivalent to scenario B of Wallhead *et al.* would probably be required.

For TOTN, GES is likely to be harder to achieve. Measured TOTN concentrations are high in most catchments and reduction targets of more than 40 % are common. In addition, traditional agricultural measures are targeted towards reducing losses of particulate material, making them effective for reducing inputs of TOTP and SS, but less effective for nitrogen. **In five out of seven catchments, neither scenario from Wallhead *et al.* is sufficient to achieve GES for TOTN**. In Sagelva, GES for TOTN is achieved by scenario B, but not scenario A. For Gansåa, neither scenario alone achieves GES for TOTN, but when combined with decommissioning of Dalen renseanlegg (underway during 2026), it is likely that scenario B would achieve GES for TOTN and scenario A would come close.

It is important to emphasise that the scenarios of Wallhead *et al.* focus on traditional packages of agricultural measures historically funded under the Regionale miljøprogram (RMP). As noted above, these are not efficient for reducing losses of agricultural nitrogen. In the Lillestrøm catchments considered in this study, future management plans should aim to combine the TOTP and SS mitigation of scenario A with additional wastewater and agricultural measures specifically targeting nitrogen. Scenario B itself is not desirable, because it typically achieves larger than necessary reductions in TOTP and SS, without effectively tackling nitrogen losses from agriculture.

```{python}
#| label: tbl-overall-summary
#| tbl-cap: "Summary of results for all catchments. *Avlastningsbhov based on monitoring only, due to high uncertainty in TEOTIL3. †GES may be achieved by this scenario in combination with decommissioning of Dalen renseanlegg, expected during 2026."
#| echo: false

import pandas as pd

# Read summary data
xl_path = r"./data/lillestrom_overall_summary.xlsx"
df = pd.read_excel(xl_path)

# Replace repeated catchment names with blanks
df["Nedbørfelt"] = df["Nedbørfelt"].where(~df["Nedbørfelt"].duplicated(), "")

wfd_col_dict = {
    "Svært god": "#5893A9",
    "God": "#6FB22C",
    "Moderat": "#FFF6A6",
    "Dårlig": "#F6A800",
    "Svært dårlig": "#E63D5C",
    "Udefinert": "#D9D9D9",
}

trend_col_dict = {
    "Synkende": "#6FB22C",
    "Ingen": "#D9D9D9",
    "Økende": "#E63D5C",
}

scen_col_dict = {
    "Ja": "#6FB22C",
    "Nei": "#E63D5C",
}


def color_from_dict(col_dict):
    def style_func(val):
        color = col_dict.get(val)
        if color is None:
            return ""

        text_color = "white" if color in ["#E63D5C", "#F6A800"] else "black"

        return f"background-color: {color}; color: {text_color};"

    return style_func


(
    df.style.hide(axis="index")
    .format(na_rep="")
    .map(
        color_from_dict(wfd_col_dict),
        subset=["Vann-Nett tilstand"],
    )
    .map(
        color_from_dict(trend_col_dict),
        subset=["Trend"],
    )
    .map(
        color_from_dict(scen_col_dict),
        subset=["Oppnådd Scenario A"],
    )
    .map(
        color_from_dict(scen_col_dict),
        subset=["Oppnådd Scenario B"],
    )
    .set_table_styles(
        [
            {
                "selector": "th.col_heading",
                "props": [("text-align", "center")],
            }
        ]
    )
    .set_properties(**{"text-align": "center"})
)
```